### ISSUE TITLE
Signalling server hosting

### ISSUE THREAD

**Issue by Michaelazzz** [Michaelazzz/VRDAVis#25]
- [x] get signalling server onto the server
- [x] set up proxy
- [x] set connection with front-end client
